source .env
docker run \
  -e PORT=3000 \
  -e DATABASE_URL=$DATABASE_URL \
  -e AUTH0_SECRET=$AUTH0_SECRET \
  -e AUTH0_BASE_URL=$AUTH0_BASE_URL \
  -e AUTH0_DOMAIN=$AUTH0_DOMAIN \
  -e AUTH0_ISSUER_BASE_URL=$AUTH0_ISSUER_BASE_URL \
  -e AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID \
  -e AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET \
  -p 3000:3000 --tty -it next-frontend:dev

