[package]
name="entity"
version="0.0.1"
edition="2021"

[lib]
path="src/mod.rs"

[features]
enable_derive_debug=[]

[dependencies]
sea-orm="0.9"
anyhow = "1.0.58"
log="0.4.17"
thiserror = "1.0"
[dev-dependencies]
tokio={version="1.0",features=["full"]}
dotenv = "0.15.0"