[package]
name="do-helper"
version="0.1.0"
edition="2021"

[dependencies]
serde = {version="1.0.139",features=["derive"]}
serde_json = "1.0.82"
serde_yaml = "0.8.26"
clap = {version="3.2.13",features=["derive"]}