import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      </main>
    </div>
  )
}


export async function getServerSideProps(context) {
  // cities and states can be fetched on the server side first
  const prisma = require("../lib/prisma").default

  return {props:{states:await prisma.state.findMany()}}
}